---
title: "Assignment 7 Nevin"
output: html_document
date: "2024-03-21"
---



```{r}
#Create a database from scratch using library RMariaDB 
library(RMariaDB)
library(DBI)
library(RSQLite)
```

```{r}
#Connect to the server using MariaDB()
con <- dbConnect(RMariaDB::MariaDB(), 
                 host = 'localhost',
                 user = 'root',
                 password = "Stockton5!",
                 port = localport)
#In order to connect to the server, we must include all of the above.
```

```{r}
df <- read.csv("data_science_salaries.csv") #reading in the data
```

```{r}
#Preview the dataframe. 
head(df)
```


```{r}
#all the column names
colnames(df)

```
```{r}
dbExecute(con, paste("CREATE DATABASE IF NOT EXISTS ", "Salaries"))
dbExecute(con, paste("USE", "Salaries"))
```

```{r}
#Create our second table in the database file using SQL statements:
#We want our table column names to match what is in the .csv file
#Every table will be different depending on your dataset.
second_table_query <- "CREATE TABLE salary (
                      id INT AUTO_INCREMENT PRIMARY KEY,
                      job_title VARCHAR(255),
                      salary_in_usd INT(255),
                      salary INT(255),
                      employment_type VARCHAR(255),
                      salary_currency VARCHAR(255)
                   






                                              );"
#Execute the query:
# Define the INSERT INTO query
insert_data_query <- "
INSERT INTO job_title (salary_in_usd, job_title, salary, employment_type) 
VALUES ('Salary in USD', 'Job Title', 'Salary', 'Employment Type')"



dbExecute(con, second_table_query)
```
```{r}
#Create our second table in the database file using SQL statements:
#We want our table column names to match what is in the .csv file
#Every table will be different depending on your dataset.
third_table_query <- "CREATE TABLE company_data (
                      id INT AUTO_INCREMENT PRIMARY KEY,
                      company_location VARCHAR(255),
                      employment_type VARCHAR (255),
                      company_size VARCHAR (255)
                   






                                              );"
#Execute the query:
# Define the INSERT INTO query
insert_data_query <- "
INSERT INTO company_data (company_location, employment_type, company_size) 
VALUES ('Company Location', 'Employment Type, 'Company Size')"            



dbExecute(con, third_table_query)
```

```{r}
#Create our second table in the database file using SQL statements:
#We want our table column names to match what is in the .csv file
#Every table will be different depending on your dataset.
fourth_table_query <- "CREATE TABLE employee_data (
                      id INT AUTO_INCREMENT PRIMARY KEY,
                      work_models VARCHAR(255),
                      job_title VARCHAR (255),
                      employee_residence VARCHAR (255),
                      experience_level VARCHAR (255)
                   






                                              );"
#Execute the query:
# Define the INSERT INTO query
insert_data_query <- "
INSERT INTO company_data (work_models, job_title, employee_residence, experience_level) 
VALUES ('Work Model', 'Job Title, 'Employee Residence,' 'Experience Level')"            



dbExecute(con, fourth_table_query)
```


```{r}
```








```{r}
#Close the database connection :)
dbDisconnect(con)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
